import type { QueryCategory } from "@/types";

export const PREBUILT_QUERY_CATEGORIES: QueryCategory[] = [
  // ═══════════════════════════════════════════
  // ACTIVE DIRECTORY
  // ═══════════════════════════════════════════
  {
    id: "domain-info",
    name: "Domain Information",
    platform: "ad",
    queries: [
      {
        id: "di-1",
        name: "Find all Domain Admins",
        description: "List all members of the Domain Admins group",
        query: `MATCH p=(n:Group)<-[:MemberOf*1..]-(m) WHERE n.name =~ "(?i)DOMAIN ADMINS@.*" RETURN p`,
        category: "domain-info",
        platform: "ad",
      },
      {
        id: "di-2",
        name: "Map Domain Trusts",
        description: "Show all trust relationships between domains",
        query: `MATCH p=(n:Domain)-[:TrustedBy]->(m:Domain) RETURN p`,
        category: "domain-info",
        platform: "ad",
      },
      {
        id: "di-3",
        name: "List all Domain Controllers",
        description: "Find all domain controller computer objects",
        query: `MATCH p=(n:Computer)-[:MemberOf*1..]->(g:Group) WHERE g.objectid ENDS WITH "-516" RETURN p`,
        category: "domain-info",
        platform: "ad",
      },
      {
        id: "di-4",
        name: "OU Structure",
        description: "Display the organizational unit hierarchy",
        query: `MATCH p=(o:OU)-[:Contains*1..]->(n) RETURN p LIMIT 200`,
        category: "domain-info",
        platform: "ad",
      },
      {
        id: "di-5",
        name: "Forest Trusts",
        description: "Map cross-forest trust relationships",
        query: `MATCH p=(n:Domain)-[:TrustedBy]-(m:Domain) WHERE NOT n.name CONTAINS m.name AND NOT m.name CONTAINS n.name RETURN p`,
        category: "domain-info",
        platform: "ad",
      },
      {
        id: "di-6",
        name: "Domain Functional Level",
        description: "Show domain names and their functional levels",
        query: `MATCH (d:Domain) RETURN d.name AS Domain, d.functionallevel AS FunctionalLevel`,
        category: "domain-info",
        platform: "ad",
      },
    ],
  },
  {
    id: "dangerous-privileges",
    name: "Dangerous Privileges",
    platform: "ad",
    queries: [
      {
        id: "dp-1",
        name: "DCSync Rights",
        description: "Principals with DCSync (GetChanges + GetChangesAll) permissions",
        query: `MATCH p=()-[:DCSync|GetChanges|GetChangesAll|GetChangesInFilteredSet]->(:Domain) RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-2",
        name: "GenericAll on Computers",
        description: "Non-admin principals with GenericAll on computers",
        query: `MATCH p=(n)-[:GenericAll]->(c:Computer) WHERE NOT n.name CONTAINS "DOMAIN ADMINS" AND NOT n.name CONTAINS "ENTERPRISE ADMINS" RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-3",
        name: "WriteDACL on Groups",
        description: "Principals with WriteDACL permission on groups",
        query: `MATCH p=(n)-[:WriteDacl]->(g:Group) RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-4",
        name: "Owns on Tier Zero",
        description: "Principals that own Tier Zero objects",
        query: `MATCH p=(n)-[:Owns]->(m) WHERE m.system_tags CONTAINS "admin_tier_0" RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-5",
        name: "Domain Users as Local Admin",
        description: "Computers where Domain Users have local admin rights",
        query: `MATCH p=(g:Group)-[:AdminTo]->(c:Computer) WHERE g.objectid ENDS WITH "-513" RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-6",
        name: "ForceChangePassword on DA Members",
        description: "Principals that can force-change Domain Admin passwords",
        query: `MATCH p=(n)-[:ForceChangePassword]->(u:User)-[:MemberOf*1..]->(g:Group) WHERE g.name =~ "(?i)DOMAIN ADMINS@.*" RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-7",
        name: "GPO Abuse Paths",
        description: "Users with write permissions on GPOs linked to privileged OUs",
        query: `MATCH p=(u)-[:GenericAll|GenericWrite|WriteOwner|WriteDacl]->(g:GPO)-[:GpLink]->(o:OU)-[:Contains*1..]->(t) WHERE t.system_tags CONTAINS "admin_tier_0" RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
      {
        id: "dp-8",
        name: "AdminSDHolder Abusers",
        description: "Principals with dangerous rights on AdminSDHolder",
        query: `MATCH p=(n)-[:GenericAll|GenericWrite|WriteDacl|WriteOwner|Owns]->(c:Container) WHERE c.name = "ADMINSDHOLDER" RETURN p`,
        category: "dangerous-privileges",
        platform: "ad",
      },
    ],
  },
  {
    id: "kerberos",
    name: "Kerberos Interaction",
    platform: "ad",
    queries: [
      {
        id: "kb-1",
        name: "Kerberoastable Users",
        description: "Enabled users with SPNs set (Kerberoastable)",
        query: `MATCH (u:User) WHERE u.hasspn = true AND u.enabled = true RETURN u.name AS User, u.serviceprincipalnames AS SPNs`,
        category: "kerberos",
        platform: "ad",
      },
      {
        id: "kb-2",
        name: "Kerberoastable Tier Zero Members",
        description: "Kerberoastable users that are Tier Zero",
        query: `MATCH (u:User) WHERE u.hasspn = true AND u.enabled = true AND u.system_tags CONTAINS "admin_tier_0" RETURN u.name AS User, u.serviceprincipalnames AS SPNs`,
        category: "kerberos",
        platform: "ad",
      },
      {
        id: "kb-3",
        name: "AS-REP Roastable Users",
        description: "Users with Kerberos pre-authentication disabled",
        query: `MATCH (u:User) WHERE u.dontreqpreauth = true AND u.enabled = true RETURN u.name AS User, u.objectid AS ObjectId`,
        category: "kerberos",
        platform: "ad",
      },
      {
        id: "kb-4",
        name: "Constrained Delegation",
        description: "Computers and users with constrained delegation configured",
        query: `MATCH (n) WHERE n.allowedtodelegate IS NOT NULL RETURN n.name AS Name, n.allowedtodelegate AS Delegates, labels(n) AS Type`,
        category: "kerberos",
        platform: "ad",
      },
      {
        id: "kb-5",
        name: "Kerberoastable Users with DA Paths",
        description: "Shortest paths from Kerberoastable users to Domain Admins",
        query: `MATCH (u:User) WHERE u.hasspn = true AND u.enabled = true MATCH (g:Group) WHERE g.name =~ "(?i)DOMAIN ADMINS@.*" MATCH p=shortestPath((u)-[*1..]->(g)) RETURN p`,
        category: "kerberos",
        platform: "ad",
      },
    ],
  },
  {
    id: "shortest-paths",
    name: "Shortest Paths",
    platform: "ad",
    queries: [
      {
        id: "sp-1",
        name: "Shortest Paths to Domain Admins",
        description: "All shortest paths to the Domain Admins group",
        query: `MATCH p=shortestPath((n)-[*1..]->(g:Group)) WHERE g.name =~ "(?i)DOMAIN ADMINS@.*" AND n<>g RETURN p LIMIT 50`,
        category: "shortest-paths",
        platform: "ad",
      },
      {
        id: "sp-2",
        name: "From Kerberoastable to DA",
        description: "Shortest paths from Kerberoastable users to Domain Admins",
        query: `MATCH (u:User) WHERE u.hasspn = true AND u.enabled = true MATCH (g:Group) WHERE g.name =~ "(?i)DOMAIN ADMINS@.*" MATCH p=shortestPath((u)-[*1..]->(g)) RETURN p LIMIT 25`,
        category: "shortest-paths",
        platform: "ad",
      },
      {
        id: "sp-3",
        name: "From Owned Principals",
        description: "Shortest paths from owned principals to Tier Zero",
        query: `MATCH p=shortestPath((n)-[*1..]->(m)) WHERE n.owned = true AND m.system_tags CONTAINS "admin_tier_0" AND n<>m RETURN p`,
        category: "shortest-paths",
        platform: "ad",
      },
      {
        id: "sp-4",
        name: "To Tier Zero",
        description: "Shortest paths to all Tier Zero assets",
        query: `MATCH p=shortestPath((n)-[*1..]->(m)) WHERE m.system_tags CONTAINS "admin_tier_0" AND NOT n.system_tags CONTAINS "admin_tier_0" AND n<>m RETURN p LIMIT 50`,
        category: "shortest-paths",
        platform: "ad",
      },
      {
        id: "sp-5",
        name: "From Domain Users",
        description: "Shortest paths from Domain Users group to high-value targets",
        query: `MATCH p=shortestPath((g:Group)-[*1..]->(m)) WHERE g.objectid ENDS WITH "-513" AND m.system_tags CONTAINS "admin_tier_0" AND g<>m RETURN p`,
        category: "shortest-paths",
        platform: "ad",
      },
      {
        id: "sp-6",
        name: "Across Domain Trusts",
        description: "Attack paths that cross domain trust boundaries",
        query: `MATCH p=shortestPath((n)-[*1..]->(m)) WHERE NOT n.domain = m.domain AND m.system_tags CONTAINS "admin_tier_0" RETURN p LIMIT 25`,
        category: "shortest-paths",
        platform: "ad",
      },
    ],
  },
  {
    id: "adcs",
    name: "ADCS",
    platform: "ad",
    queries: [
      {
        id: "cs-1",
        name: "PKI Hierarchy",
        description: "Map the certificate authority hierarchy",
        query: `MATCH p=(:RootCA)-[:RootCAFor|IssuedSignedBy|EnterpriseCAFor|NTAuthStoreFor*1..]->() RETURN p`,
        category: "adcs",
        platform: "ad",
      },
      {
        id: "cs-2",
        name: "ESC1 Vulnerable Templates",
        description: "Certificate templates vulnerable to ESC1 (enrollee supplies subject)",
        query: `MATCH (ct:CertTemplate) WHERE ct.enrolleesuppliessubject = true AND ct.enabled = true AND ct.requiresmanagerapproval = false MATCH p=()-[:Enroll|AutoEnroll]->(ct)-[:PublishedTo]->(:EnterpriseCA) RETURN p`,
        category: "adcs",
        platform: "ad",
      },
      {
        id: "cs-3",
        name: "ESC4 Vulnerable Templates",
        description: "Templates where non-admins can modify template settings",
        query: `MATCH p=(n)-[:GenericAll|GenericWrite|WriteDacl|WriteOwner|Owns]->(ct:CertTemplate)-[:PublishedTo]->(:EnterpriseCA) WHERE NOT n.name CONTAINS "DOMAIN ADMINS" AND NOT n.name CONTAINS "ENTERPRISE ADMINS" RETURN p`,
        category: "adcs",
        platform: "ad",
      },
      {
        id: "cs-4",
        name: "ESC6 Vulnerable CAs",
        description: "Enterprise CAs with EDITF_ATTRIBUTESUBJECTALTNAME2 enabled",
        query: `MATCH (eca:EnterpriseCA) WHERE eca.isuserspecifiessanenabled = true MATCH p=()-[:Enroll|AutoEnroll]->(:CertTemplate)-[:PublishedTo]->(eca) RETURN p`,
        category: "adcs",
        platform: "ad",
      },
      {
        id: "cs-5",
        name: "CA Administrators",
        description: "Principals with administrative access to Certificate Authorities",
        query: `MATCH p=(n)-[:ManageCertificates|ManageCA|Enroll]->(eca:EnterpriseCA) RETURN p`,
        category: "adcs",
        platform: "ad",
      },
      {
        id: "cs-6",
        name: "Enrollment Agents",
        description: "Principals that can act as enrollment agents",
        query: `MATCH p=(n)-[:Enroll]->(ct:CertTemplate)-[:PublishedTo]->(eca:EnterpriseCA) WHERE ct.schemaversion >= 2 AND ct.authorizedsignatures > 0 RETURN p`,
        category: "adcs",
        platform: "ad",
      },
    ],
  },
  {
    id: "ad-hygiene",
    name: "AD Hygiene",
    platform: "ad",
    queries: [
      {
        id: "ah-1",
        name: "Inactive/Stale Users",
        description: "Enabled users that haven't logged in for 90+ days",
        query: `MATCH (u:User) WHERE u.enabled = true AND u.lastlogontimestamp < (datetime().epochseconds - (90 * 86400)) AND u.lastlogontimestamp > 0 RETURN u.name AS User, u.lastlogontimestamp AS LastLogon ORDER BY u.lastlogontimestamp ASC LIMIT 100`,
        category: "ad-hygiene",
        platform: "ad",
      },
      {
        id: "ah-2",
        name: "Non-Expiring Passwords",
        description: "Enabled users with passwords set to never expire",
        query: `MATCH (u:User) WHERE u.pwdneverexpires = true AND u.enabled = true RETURN u.name AS User, u.objectid AS ObjectId`,
        category: "ad-hygiene",
        platform: "ad",
      },
      {
        id: "ah-3",
        name: "Disabled Users in Privileged Groups",
        description: "Disabled user accounts that are still members of privileged groups",
        query: `MATCH p=(u:User)-[:MemberOf*1..]->(g:Group) WHERE u.enabled = false AND g.system_tags CONTAINS "admin_tier_0" RETURN p`,
        category: "ad-hygiene",
        platform: "ad",
      },
      {
        id: "ah-4",
        name: "Computers without LAPS",
        description: "Computers that don't have LAPS configured",
        query: `MATCH (c:Computer) WHERE c.haslaps = false AND c.enabled = true RETURN c.name AS Computer, c.operatingsystem AS OS`,
        category: "ad-hygiene",
        platform: "ad",
      },
      {
        id: "ah-5",
        name: "Users without Kerberos Pre-auth",
        description: "Users with Kerberos pre-authentication disabled (AS-REP Roastable)",
        query: `MATCH (u:User) WHERE u.dontreqpreauth = true AND u.enabled = true RETURN u.name AS User, u.objectid AS ObjectId`,
        category: "ad-hygiene",
        platform: "ad",
      },
      {
        id: "ah-6",
        name: "Stale Computer Accounts",
        description: "Enabled computers that haven't been seen in 90+ days",
        query: `MATCH (c:Computer) WHERE c.enabled = true AND c.lastlogontimestamp < (datetime().epochseconds - (90 * 86400)) AND c.lastlogontimestamp > 0 RETURN c.name AS Computer, c.operatingsystem AS OS, c.lastlogontimestamp AS LastLogon ORDER BY c.lastlogontimestamp ASC LIMIT 100`,
        category: "ad-hygiene",
        platform: "ad",
      },
    ],
  },
  {
    id: "ntlm-relay",
    name: "NTLM Relay",
    platform: "ad",
    queries: [
      {
        id: "nr-1",
        name: "Coerce-and-Relay Attack Paths",
        description: "Paths where coercion and relay attacks are possible",
        query: `MATCH p=(c1:Computer)-[:CoerceAndRelayNTLMToSMB]->(c2:Computer) RETURN p LIMIT 50`,
        category: "ntlm-relay",
        platform: "ad",
      },
      {
        id: "nr-2",
        name: "DCs Vulnerable to NTLM Relay",
        description: "Domain controllers that may be vulnerable to NTLM relay attacks",
        query: `MATCH (c:Computer)-[:MemberOf*1..]->(g:Group) WHERE g.objectid ENDS WITH "-516" MATCH p=(n)-[:CoerceAndRelayNTLMToSMB]->(c) RETURN p`,
        category: "ntlm-relay",
        platform: "ad",
      },
      {
        id: "nr-3",
        name: "Computers with WebClient Enabled",
        description: "Computers running the WebClient service (enables HTTP-based coercion)",
        query: `MATCH (c:Computer) WHERE c.webclientrunning = true RETURN c.name AS Computer, c.operatingsystem AS OS`,
        category: "ntlm-relay",
        platform: "ad",
      },
      {
        id: "nr-4",
        name: "NTLM Relay to ADCS",
        description: "NTLM relay paths targeting AD Certificate Services enrollment endpoints",
        query: `MATCH p=()-[:CoerceAndRelayNTLMToSMB|CoerceAndRelayNTLMToHTTP]->(:EnterpriseCA) RETURN p`,
        category: "ntlm-relay",
        platform: "ad",
      },
    ],
  },

  // ═══════════════════════════════════════════
  // AZURE
  // ═══════════════════════════════════════════
  {
    id: "azure-general",
    name: "Azure General",
    platform: "azure",
    queries: [
      {
        id: "ag-1",
        name: "All Global Administrators",
        description: "List all principals with the Global Administrator role",
        query: `MATCH p=(n)-[:AZHasRole|AZMemberOf*1..]->(r:AZRole) WHERE r.name =~ "(?i)GLOBAL ADMINISTRATOR.*" RETURN p`,
        category: "azure-general",
        platform: "azure",
      },
      {
        id: "ag-2",
        name: "High Privileged Role Members",
        description: "Members of high-impact Azure AD roles",
        query: `MATCH p=(n)-[:AZHasRole|AZMemberOf*1..]->(r:AZRole) WHERE r.name =~ "(?i).*(ADMIN|CONTRIBUTOR|OWNER).*" RETURN p LIMIT 100`,
        category: "azure-general",
        platform: "azure",
      },
      {
        id: "ag-3",
        name: "App Registrations with Secrets",
        description: "Azure applications that have secrets or certificates configured",
        query: `MATCH (app:AZApp) WHERE app.passwordcredentials > 0 OR app.keycredentials > 0 RETURN app.name AS Application, app.passwordcredentials AS Passwords, app.keycredentials AS Keys`,
        category: "azure-general",
        platform: "azure",
      },
      {
        id: "ag-4",
        name: "Service Principals with Dangerous Permissions",
        description: "Service principals with high-privilege API permissions",
        query: `MATCH p=(sp:AZServicePrincipal)-[:AZMGAppRoleAssignment_ReadWrite_All|AZMGApplication_ReadWrite_All|AZMGDirectory_ReadWrite_All|AZMGRoleManagement_ReadWrite_Directory]->(r:AZTenant) RETURN p`,
        category: "azure-general",
        platform: "azure",
      },
    ],
  },
  {
    id: "azure-shortest-paths",
    name: "Azure Shortest Paths",
    platform: "azure",
    queries: [
      {
        id: "asp-1",
        name: "To Azure Tier Zero",
        description: "Shortest paths to Azure Tier Zero assets",
        query: `MATCH p=shortestPath((n)-[*1..]->(m)) WHERE m.system_tags CONTAINS "admin_tier_0" AND NOT n.system_tags CONTAINS "admin_tier_0" AND n<>m AND (n:AZUser OR n:AZServicePrincipal) RETURN p LIMIT 25`,
        category: "azure-shortest-paths",
        platform: "azure",
      },
      {
        id: "asp-2",
        name: "From Entra Users to Subscriptions",
        description: "Attack paths from Entra ID users to Azure subscriptions",
        query: `MATCH p=shortestPath((u:AZUser)-[*1..]->(s:AZSubscription)) RETURN p LIMIT 25`,
        category: "azure-shortest-paths",
        platform: "azure",
      },
      {
        id: "asp-3",
        name: "To Key Vaults",
        description: "Shortest paths to Azure Key Vaults",
        query: `MATCH p=shortestPath((n)-[*1..]->(kv:AZKeyVault)) WHERE n<>kv RETURN p LIMIT 25`,
        category: "azure-shortest-paths",
        platform: "azure",
      },
    ],
  },
  {
    id: "ms-graph",
    name: "MS Graph",
    platform: "azure",
    queries: [
      {
        id: "mg-1",
        name: "Service Principals with MS Graph App Roles",
        description: "Service principals with dangerous Microsoft Graph API permissions",
        query: `MATCH p=(sp:AZServicePrincipal)-[:AZMGAppRoleAssignment_ReadWrite_All|AZMGApplication_ReadWrite_All|AZMGDirectory_ReadWrite_All|AZMGRoleManagement_ReadWrite_Directory|AZMGServicePrincipalEndpoint_ReadWrite_All]->(t:AZTenant) RETURN p`,
        category: "ms-graph",
        platform: "azure",
      },
      {
        id: "mg-2",
        name: "Applications with Directory Role Assignments",
        description: "Applications and service principals with directory role assignments",
        query: `MATCH p=(app:AZApp)-[:AZRunsAs]->(sp:AZServicePrincipal)-[:AZHasRole]->(r:AZRole) RETURN p`,
        category: "ms-graph",
        platform: "azure",
      },
    ],
  },
  {
    id: "azure-hygiene",
    name: "Azure Hygiene",
    platform: "azure",
    queries: [
      {
        id: "azh-1",
        name: "Foreign Principals in Tier Zero",
        description: "External/guest principals with Tier Zero access",
        query: `MATCH p=(n)-[*1..]->(m) WHERE m.system_tags CONTAINS "admin_tier_0" AND n.userprincipalname CONTAINS "#EXT#" RETURN p`,
        category: "azure-hygiene",
        platform: "azure",
      },
      {
        id: "azh-2",
        name: "Synced Tier Zero AD Principals",
        description: "On-premises synced accounts with Tier Zero Azure roles",
        query: `MATCH p=(u:User)-[:SyncedToEntraUser]->(au:AZUser)-[:AZHasRole|AZMemberOf*1..]->(r) WHERE r.system_tags CONTAINS "admin_tier_0" RETURN p`,
        category: "azure-hygiene",
        platform: "azure",
      },
      {
        id: "azh-3",
        name: "Stale App Registrations",
        description: "Azure applications without recent sign-in activity",
        query: `MATCH (app:AZApp)-[:AZRunsAs]->(sp:AZServicePrincipal) WHERE sp.lastsignin IS NOT NULL RETURN app.name AS Application, sp.lastsignin AS LastSignIn ORDER BY sp.lastsignin ASC LIMIT 50`,
        category: "azure-hygiene",
        platform: "azure",
      },
    ],
  },

  // ═══════════════════════════════════════════
  // CROSS PLATFORM
  // ═══════════════════════════════════════════
  {
    id: "cross-platform",
    name: "Cross Platform",
    platform: "cross",
    queries: [
      {
        id: "cp-1",
        name: "Synced Users in Domain Admins",
        description: "Azure-synced users that are members of Domain Admins",
        query: `MATCH p=(au:AZUser)<-[:SyncedToEntraUser]-(u:User)-[:MemberOf*1..]->(g:Group) WHERE g.name =~ "(?i)DOMAIN ADMINS@.*" RETURN p`,
        category: "cross-platform",
        platform: "cross",
      },
      {
        id: "cp-2",
        name: "On-prem Users with Entra Admin Roles",
        description: "On-premises users synced to Entra ID with administrative roles",
        query: `MATCH p=(u:User)-[:SyncedToEntraUser]->(au:AZUser)-[:AZHasRole]->(r:AZRole) RETURN p`,
        category: "cross-platform",
        platform: "cross",
      },
      {
        id: "cp-3",
        name: "Hybrid Attack Paths",
        description: "Attack paths that traverse from on-prem AD to Azure or vice versa",
        query: `MATCH p=shortestPath((n:User)-[*1..]->(m)) WHERE m.system_tags CONTAINS "admin_tier_0" AND (m:AZUser OR m:AZServicePrincipal OR m:AZRole) RETURN p LIMIT 25`,
        category: "cross-platform",
        platform: "cross",
      },
      {
        id: "cp-4",
        name: "Synced Users with Dangerous Permissions",
        description: "Synced accounts with high-privilege access in both environments",
        query: `MATCH (u:User)-[:SyncedToEntraUser]->(au:AZUser) WHERE u.system_tags CONTAINS "admin_tier_0" OR au.system_tags CONTAINS "admin_tier_0" RETURN u.name AS OnPremUser, au.name AS EntraUser`,
        category: "cross-platform",
        platform: "cross",
      },
    ],
  },
];
